# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ServiceAvailable(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'location': 'str',
        'count': 'int',
        'plan_count': 'list[ServicePlanAvailable]'
    }

    attribute_map = {
        'location': 'location',
        'count': 'count',
        'plan_count': 'plan_count'
    }

    def __init__(self, location=None, count=None, plan_count=None):  # noqa: E501
        """ServiceAvailable - a model defined in OpenAPI"""  # noqa: E501

        self._location = None
        self._count = None
        self._plan_count = None
        self.discriminator = None

        if location is not None:
            self.location = location
        if count is not None:
            self.count = count
        if plan_count is not None:
            self.plan_count = plan_count

    @property
    def location(self):
        """Gets the location of this ServiceAvailable.  # noqa: E501


        :return: The location of this ServiceAvailable.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this ServiceAvailable.


        :param location: The location of this ServiceAvailable.  # noqa: E501
        :type: str
        """
        if location is not None and len(location) > 36:
            raise ValueError("Invalid value for `location`, length must be less than or equal to `36`")  # noqa: E501
        if location is not None and len(location) < 36:
            raise ValueError("Invalid value for `location`, length must be greater than or equal to `36`")  # noqa: E501

        self._location = location

    @property
    def count(self):
        """Gets the count of this ServiceAvailable.  # noqa: E501


        :return: The count of this ServiceAvailable.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this ServiceAvailable.


        :param count: The count of this ServiceAvailable.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def plan_count(self):
        """Gets the plan_count of this ServiceAvailable.  # noqa: E501


        :return: The plan_count of this ServiceAvailable.  # noqa: E501
        :rtype: list[ServicePlanAvailable]
        """
        return self._plan_count

    @plan_count.setter
    def plan_count(self, plan_count):
        """Sets the plan_count of this ServiceAvailable.


        :param plan_count: The plan_count of this ServiceAvailable.  # noqa: E501
        :type: list[ServicePlanAvailable]
        """

        self._plan_count = plan_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceAvailable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
