# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ServicePlanAvailable(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'plan_uuid': 'str',
        'count': 'int'
    }

    attribute_map = {
        'plan_uuid': 'plan_uuid',
        'count': 'count'
    }

    def __init__(self, plan_uuid=None, count=None):  # noqa: E501
        """ServicePlanAvailable - a model defined in OpenAPI"""  # noqa: E501

        self._plan_uuid = None
        self._count = None
        self.discriminator = None

        if plan_uuid is not None:
            self.plan_uuid = plan_uuid
        if count is not None:
            self.count = count

    @property
    def plan_uuid(self):
        """Gets the plan_uuid of this ServicePlanAvailable.  # noqa: E501


        :return: The plan_uuid of this ServicePlanAvailable.  # noqa: E501
        :rtype: str
        """
        return self._plan_uuid

    @plan_uuid.setter
    def plan_uuid(self, plan_uuid):
        """Sets the plan_uuid of this ServicePlanAvailable.


        :param plan_uuid: The plan_uuid of this ServicePlanAvailable.  # noqa: E501
        :type: str
        """
        if plan_uuid is not None and len(plan_uuid) > 36:
            raise ValueError("Invalid value for `plan_uuid`, length must be less than or equal to `36`")  # noqa: E501
        if plan_uuid is not None and len(plan_uuid) < 36:
            raise ValueError("Invalid value for `plan_uuid`, length must be greater than or equal to `36`")  # noqa: E501

        self._plan_uuid = plan_uuid

    @property
    def count(self):
        """Gets the count of this ServicePlanAvailable.  # noqa: E501


        :return: The count of this ServicePlanAvailable.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this ServicePlanAvailable.


        :param count: The count of this ServicePlanAvailable.  # noqa: E501
        :type: int
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServicePlanAvailable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
