# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ActiveTask(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'progress': 'int',
        'task_name': 'str',
        'task_id': 'str'
    }

    attribute_map = {
        'progress': 'progress',
        'task_name': 'task_name',
        'task_id': 'task_id'
    }

    def __init__(self, progress=None, task_name=None, task_id=None):  # noqa: E501
        """ActiveTask - a model defined in OpenAPI"""  # noqa: E501

        self._progress = None
        self._task_name = None
        self._task_id = None
        self.discriminator = None

        if progress is not None:
            self.progress = progress
        if task_name is not None:
            self.task_name = task_name
        if task_id is not None:
            self.task_id = task_id

    @property
    def progress(self):
        """Gets the progress of this ActiveTask.  # noqa: E501


        :return: The progress of this ActiveTask.  # noqa: E501
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this ActiveTask.


        :param progress: The progress of this ActiveTask.  # noqa: E501
        :type: int
        """

        self._progress = progress

    @property
    def task_name(self):
        """Gets the task_name of this ActiveTask.  # noqa: E501


        :return: The task_name of this ActiveTask.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this ActiveTask.


        :param task_name: The task_name of this ActiveTask.  # noqa: E501
        :type: str
        """

        self._task_name = task_name

    @property
    def task_id(self):
        """Gets the task_id of this ActiveTask.  # noqa: E501


        :return: The task_id of this ActiveTask.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this ActiveTask.


        :param task_id: The task_id of this ActiveTask.  # noqa: E501
        :type: str
        """
        if task_id is not None and len(task_id) > 36:
            raise ValueError("Invalid value for `task_id`, length must be less than or equal to `36`")  # noqa: E501
        if task_id is not None and len(task_id) < 36:
            raise ValueError("Invalid value for `task_id`, length must be greater than or equal to `36`")  # noqa: E501

        self._task_id = task_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActiveTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
