# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class IPv4Input(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ipv4_address': 'str',
        'ipv4_netmask': 'str',
        'ipv4_gateway': 'str'
    }

    attribute_map = {
        'ipv4_address': 'ipv4_address',
        'ipv4_netmask': 'ipv4_netmask',
        'ipv4_gateway': 'ipv4_gateway'
    }

    def __init__(self, ipv4_address=None, ipv4_netmask=None, ipv4_gateway=None):  # noqa: E501
        """IPv4Input - a model defined in OpenAPI"""  # noqa: E501

        self._ipv4_address = None
        self._ipv4_netmask = None
        self._ipv4_gateway = None
        self.discriminator = None

        if ipv4_address is not None:
            self.ipv4_address = ipv4_address
        if ipv4_netmask is not None:
            self.ipv4_netmask = ipv4_netmask
        if ipv4_gateway is not None:
            self.ipv4_gateway = ipv4_gateway

    @property
    def ipv4_address(self):
        """Gets the ipv4_address of this IPv4Input.  # noqa: E501


        :return: The ipv4_address of this IPv4Input.  # noqa: E501
        :rtype: str
        """
        return self._ipv4_address

    @ipv4_address.setter
    def ipv4_address(self, ipv4_address):
        """Sets the ipv4_address of this IPv4Input.


        :param ipv4_address: The ipv4_address of this IPv4Input.  # noqa: E501
        :type: str
        """
        if ipv4_address is not None and len(ipv4_address) > 43:
            raise ValueError("Invalid value for `ipv4_address`, length must be less than or equal to `43`")  # noqa: E501
        if ipv4_address is not None and len(ipv4_address) < 6:
            raise ValueError("Invalid value for `ipv4_address`, length must be greater than or equal to `6`")  # noqa: E501

        self._ipv4_address = ipv4_address

    @property
    def ipv4_netmask(self):
        """Gets the ipv4_netmask of this IPv4Input.  # noqa: E501


        :return: The ipv4_netmask of this IPv4Input.  # noqa: E501
        :rtype: str
        """
        return self._ipv4_netmask

    @ipv4_netmask.setter
    def ipv4_netmask(self, ipv4_netmask):
        """Sets the ipv4_netmask of this IPv4Input.


        :param ipv4_netmask: The ipv4_netmask of this IPv4Input.  # noqa: E501
        :type: str
        """
        if ipv4_netmask is not None and len(ipv4_netmask) > 43:
            raise ValueError("Invalid value for `ipv4_netmask`, length must be less than or equal to `43`")  # noqa: E501
        if ipv4_netmask is not None and len(ipv4_netmask) < 6:
            raise ValueError("Invalid value for `ipv4_netmask`, length must be greater than or equal to `6`")  # noqa: E501

        self._ipv4_netmask = ipv4_netmask

    @property
    def ipv4_gateway(self):
        """Gets the ipv4_gateway of this IPv4Input.  # noqa: E501


        :return: The ipv4_gateway of this IPv4Input.  # noqa: E501
        :rtype: str
        """
        return self._ipv4_gateway

    @ipv4_gateway.setter
    def ipv4_gateway(self, ipv4_gateway):
        """Sets the ipv4_gateway of this IPv4Input.


        :param ipv4_gateway: The ipv4_gateway of this IPv4Input.  # noqa: E501
        :type: str
        """
        if ipv4_gateway is not None and len(ipv4_gateway) > 43:
            raise ValueError("Invalid value for `ipv4_gateway`, length must be less than or equal to `43`")  # noqa: E501
        if ipv4_gateway is not None and len(ipv4_gateway) < 6:
            raise ValueError("Invalid value for `ipv4_gateway`, length must be greater than or equal to `6`")  # noqa: E501

        self._ipv4_gateway = ipv4_gateway

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IPv4Input):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
