# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NetworkLimitUpdateModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'next_limit_type': 'str'
    }

    attribute_map = {
        'next_limit_type': 'next_limit_type'
    }

    def __init__(self, next_limit_type=None):  # noqa: E501
        """NetworkLimitUpdateModel - a model defined in OpenAPI"""  # noqa: E501

        self._next_limit_type = None
        self.discriminator = None

        if next_limit_type is not None:
            self.next_limit_type = next_limit_type

    @property
    def next_limit_type(self):
        """Gets the next_limit_type of this NetworkLimitUpdateModel.  # noqa: E501


        :return: The next_limit_type of this NetworkLimitUpdateModel.  # noqa: E501
        :rtype: str
        """
        return self._next_limit_type

    @next_limit_type.setter
    def next_limit_type(self, next_limit_type):
        """Sets the next_limit_type of this NetworkLimitUpdateModel.


        :param next_limit_type: The next_limit_type of this NetworkLimitUpdateModel.  # noqa: E501
        :type: str
        """

        self._next_limit_type = next_limit_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkLimitUpdateModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
