# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PriceModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'rub': 'PricePeriodModel',
        'eur': 'PricePeriodModel',
        'usd': 'PricePeriodModel'
    }

    attribute_map = {
        'rub': 'RUB',
        'eur': 'EUR',
        'usd': 'USD'
    }

    def __init__(self, rub=None, eur=None, usd=None):  # noqa: E501
        """PriceModel - a model defined in OpenAPI"""  # noqa: E501

        self._rub = None
        self._eur = None
        self._usd = None
        self.discriminator = None

        self.rub = rub
        self.eur = eur
        self.usd = usd

    @property
    def rub(self):
        """Gets the rub of this PriceModel.  # noqa: E501


        :return: The rub of this PriceModel.  # noqa: E501
        :rtype: PricePeriodModel
        """
        return self._rub

    @rub.setter
    def rub(self, rub):
        """Sets the rub of this PriceModel.


        :param rub: The rub of this PriceModel.  # noqa: E501
        :type: PricePeriodModel
        """
        if rub is None:
            raise ValueError("Invalid value for `rub`, must not be `None`")  # noqa: E501

        self._rub = rub

    @property
    def eur(self):
        """Gets the eur of this PriceModel.  # noqa: E501


        :return: The eur of this PriceModel.  # noqa: E501
        :rtype: PricePeriodModel
        """
        return self._eur

    @eur.setter
    def eur(self, eur):
        """Sets the eur of this PriceModel.


        :param eur: The eur of this PriceModel.  # noqa: E501
        :type: PricePeriodModel
        """
        if eur is None:
            raise ValueError("Invalid value for `eur`, must not be `None`")  # noqa: E501

        self._eur = eur

    @property
    def usd(self):
        """Gets the usd of this PriceModel.  # noqa: E501


        :return: The usd of this PriceModel.  # noqa: E501
        :rtype: PricePeriodModel
        """
        return self._usd

    @usd.setter
    def usd(self, usd):
        """Sets the usd of this PriceModel.


        :param usd: The usd of this PriceModel.  # noqa: E501
        :type: PricePeriodModel
        """
        if usd is None:
            raise ValueError("Invalid value for `usd`, must not be `None`")  # noqa: E501

        self._usd = usd

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PriceModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
