# coding: utf-8

"""
    Seido User REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.4.8
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ResourceUpdateModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'price_plan_uuid': 'str',
        'user_desc': 'str',
        'demo': 'bool'
    }

    attribute_map = {
        'price_plan_uuid': 'price_plan_uuid',
        'user_desc': 'user_desc',
        'demo': 'demo'
    }

    def __init__(self, price_plan_uuid=None, user_desc=None, demo=None):  # noqa: E501
        """ResourceUpdateModel - a model defined in OpenAPI"""  # noqa: E501

        self._price_plan_uuid = None
        self._user_desc = None
        self._demo = None
        self.discriminator = None

        if price_plan_uuid is not None:
            self.price_plan_uuid = price_plan_uuid
        if user_desc is not None:
            self.user_desc = user_desc
        if demo is not None:
            self.demo = demo

    @property
    def price_plan_uuid(self):
        """Gets the price_plan_uuid of this ResourceUpdateModel.  # noqa: E501


        :return: The price_plan_uuid of this ResourceUpdateModel.  # noqa: E501
        :rtype: str
        """
        return self._price_plan_uuid

    @price_plan_uuid.setter
    def price_plan_uuid(self, price_plan_uuid):
        """Sets the price_plan_uuid of this ResourceUpdateModel.


        :param price_plan_uuid: The price_plan_uuid of this ResourceUpdateModel.  # noqa: E501
        :type: str
        """
        if price_plan_uuid is not None and len(price_plan_uuid) > 36:
            raise ValueError("Invalid value for `price_plan_uuid`, length must be less than or equal to `36`")  # noqa: E501
        if price_plan_uuid is not None and len(price_plan_uuid) < 36:
            raise ValueError("Invalid value for `price_plan_uuid`, length must be greater than or equal to `36`")  # noqa: E501

        self._price_plan_uuid = price_plan_uuid

    @property
    def user_desc(self):
        """Gets the user_desc of this ResourceUpdateModel.  # noqa: E501


        :return: The user_desc of this ResourceUpdateModel.  # noqa: E501
        :rtype: str
        """
        return self._user_desc

    @user_desc.setter
    def user_desc(self, user_desc):
        """Sets the user_desc of this ResourceUpdateModel.


        :param user_desc: The user_desc of this ResourceUpdateModel.  # noqa: E501
        :type: str
        """

        self._user_desc = user_desc

    @property
    def demo(self):
        """Gets the demo of this ResourceUpdateModel.  # noqa: E501


        :return: The demo of this ResourceUpdateModel.  # noqa: E501
        :rtype: bool
        """
        return self._demo

    @demo.setter
    def demo(self, demo):
        """Sets the demo of this ResourceUpdateModel.


        :param demo: The demo of this ResourceUpdateModel.  # noqa: E501
        :type: bool
        """

        self._demo = demo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceUpdateModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
